# Generated by Django 5.0.6 on 2025-01-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0004_alter_leads_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='organisation',
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to='Leads.userprofile',
            ),
            preserve_default=False,
        ),
    ]
