# Generated by Django 5.0.6 on 2025-01-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0009_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='Leads.userprofile'
            ),
        ),
    ]
