# Generated by Django 5.0.6 on 2025-01-13 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0010_alter_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads',
                to='Leads.category',
            ),
        ),
    ]
