repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0  # Check https://github.com/psf/black for the latest version
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "2.7.1"
    hooks:
      - id: prettier
        files: "\\.(html|css|js)$"
